---
- name: install dhcpcd client
  become: true
  package:
    name: dhcpcd5
  when: dhcpcd_install_packages

- name: configure global dhcpcd config values
  become: true
  lineinfile:
    path: "{{ dhcpcd_config_path }}"
    regexp: "^{{ item.keyword }}"
    line: "{{ item.keyword }} {{ item.value | default('') }}"
    state: "{{ item.state | default('present') }}"
    insertbefore: BOF
  loop: "{{ dhcpcd_global_config }}"
  notify: reconfigure dhcpcd

- name: configure dhcpcd interfaces
  become: true
  blockinfile:
    path: "{{ dhcpcd_config_path }}"
    marker: "### {mark} ANSIBLE MANAGED BLOCK {{ item.name }} ###"
    block: |
      interface {{ item.name }}
      {{ item.config | default("") }}
  loop: "{{ dhcpcd_interface_config }}"
  notify: reconfigure dhcpcd

- name: purge legacy dhclient
  become: true
  package:
    name: isc-dhcp-client
    state: absent
  when: dhcpcd_remove_dhclient
  notify: terminate dhclient processes
