---
- name: install dhcpcd client
  become: yes
  package:
    name: dhcpcd5

- name: configure global dhcpcd config values
  become: yes
  lineinfile:
    path: "{{ dhcpcd_config_path }}"
    regexp: "^{{ item.keyword }}"
    line: "{{ item.keyword }} {{ item.value | default('') }}"
    state: "{{ item.state | default('present') }}"
    insertbefore: BOF
  loop: "{{ dhcpcd_global_config }}"

- name: configure dhcpcd interfaces
  become: yes
  blockinfile:
    path: "{{ dhcpcd_config_path }}"
    marker: "### {mark} ANSIBLE MANAGED BLOCK {{ item.name }} ###"
    block: |
      interface {{ item.name }}
      {{ item.config | default("") }}
  loop: "{{ dhcpcd_interface_config }}"

- name: purge legacy dhclient
  become: yes
  package:
    name: isc-dhcp-client
    state: absent
