- name: reconfigure dhcpcd
  service:
    name: dhcpcd
    state: restarted

- name: terminate dhclient processes
  command: killall -q dhclient
  register: result
  failed_when:
    - result.rc != 0 and result.rc != 1
